[package]
name = "emcu-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.4"
cortex-m-rt = { version = "0.7.1", optional = true }
vcell = "0.1.3"

[features]
rt = ["cortex-m-rt"]
